/** @type {import("eslint").Linter.Config} */
module.exports = {
  env: {
    "es6": true,
    "browser": true,
    "node": false
  },
  extends: [
    "eslint:recommended",
  ],
  rules: {
    // Regular eslint
    "accessor-pairs": "warn",
    "array-callback-return": ["warn", {
      "allowImplicit": false, // Une fonction de mapping ne peut retourner implicitement un undefined.
      "checkForEach": false, // les forEach ne doivent rien retourner.
    }],
    "block-scoped-var": "warn",
    "brace-style": "warn",
    "complexity": "warn",
    "consistent-return": "off", // 20/24/2021: A tester si il y a pas erreurs manquées
    "curly": ["warn", "all"],
    "default-case-last": "warn",
    "default-case": "warn",
    "default-param-last": "warn",
    "dot-location": ["warn", "property"],
    "dot-notation": "warn",
    "eqeqeq": "warn",
    "grouped-accessor-pairs": "warn",
    "guard-for-in": "warn",
    "no-alert": "warn",
    "no-array-constructor": "warn",
    "no-await-in-loop": "warn",
    "no-caller": "warn",
    "no-constructor-return": "error",
    "no-debugger": "warn",
    "no-else-return": "off",
    "no-empty": "warn",
    "no-eq-null": "warn",
    "no-eval": "warn",
    "no-extend-native": "error",
    "no-extra-bind": "warn",
    "no-extra-boolean-cast": "off",
    "no-extra-semi": "warn",
    "no-floating-decimal": "warn",
    "no-implicit-coercion": ["warn", { "number": false, "boolean": false }],
    "no-implicit-globals": "warn",
    "no-implied-eval": "error",
    "no-invalid-this": "warn",
    "no-iterator": "error",
    "no-lone-blocks": "warn",
    "no-loop-func": "error",
    "no-loss-of-precision": "warn",
    "no-multi-spaces": "warn",
    "no-multi-str": "warn",
    "no-new-func": "warn",
    "no-new-object": "warn",
    "no-new-wrappers": "warn",
    "no-new": "warn",
    "no-nonoctal-decimal-escape": "error",
    "no-octal-escape": "error",
    "no-param-reassign": "warn",
    "no-promise-executor-return": "warn",
    "no-proto": "error",
    "no-return-assign": "error",
    "no-return-await": "warn",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "warn",
    "no-shadow": "warn",
    "no-template-curly-in-string": "error",
    "no-throw-literal": "error",
    "no-trailing-spaces": "warn",
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": "warn",
    "no-unsafe-optional-chaining": "warn",
    "no-unused-expressions": "warn",
    "no-unused-vars": "warn",
    "no-useless-call": "warn",
    "no-useless-concat": "warn",
    "no-useless-escape": "off",
    "no-warning-comments": "warn",
    "prefer-arrow-callback": "warn",
    "prefer-const": "warn",
    "prefer-named-capture-group": "off",
    "prefer-numeric-literals": "warn",
    "prefer-object-spread": "warn",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": "warn",
    "prefer-rest-params": "warn",
    "prefer-spread": "warn",
    "quotes": ["warn", "double"],
    "radix": "error",
    "require-jsdoc": "warn",
    "semi-style": ["warn", "last"],
    "semi": "warn",
    "space-in-parens": "warn",
    "spaced-comment": ["warn", "always"],
    "strict": "error",
    "symbol-description": "error",
    "wrap-iife": ["warn", "inside"],
    "yoda": ["warn", "never"],
  },
  ignorePatterns: [
    "*.ts", "*.d.ts"
  ]
};